apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # If application is deleted, resource itself is deleted
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
  name: example-manifest
  namespace: argocd
spec:
  destination:
    namespace: argocd # where the child app manifests will be created/applied
    name: in-cluster
  project: default
  source:
    path: manifests/example
    repoURL: https://github.com/kevin-kho/example-manifest-deployment
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
# istio-base
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # If application is deleted, resource itself is deleted
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
  name: istio-base
  namespace: argocd
spec:
  destination:
    namespace: argocd # where the child app manifests will be created/applied
    name: in-cluster
  project: default
  source:
    path: manifests/istio/base/out
    repoURL: https://github.com/kevin-kho/example-manifest-deployment
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      jsonPointers:
        - /webhooks/0/failurePolicy

---
# istio-cni
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # If application is deleted, resource itself is deleted
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
  name: istio-cni
  namespace: argocd
spec:
  destination:
    namespace: argocd # where the child app manifests will be created/applied
    name: in-cluster
  project: default
  source:
    path: manifests/istio/cni/out
    repoURL: https://github.com/kevin-kho/example-manifest-deployment
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
# istio-istiod
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # If application is deleted, resource itself is deleted
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
  name: istio-istiod
  namespace: argocd
spec:
  destination:
    namespace: argocd # where the child app manifests will be created/applied
    name: in-cluster
  project: default
  source:
    path: manifests/istio/istiod/out
    repoURL: https://github.com/kevin-kho/example-manifest-deployment
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# istio-gateways
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # If application is deleted, resource itself is deleted
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
  name: istio-gateways
  namespace: argocd
spec:
  destination:
    namespace: argocd # where the child app manifests will be created/applied
    name: in-cluster
  project: default
  source:
    path: manifests/istio/gateways/out
    repoURL: https://github.com/kevin-kho/example-manifest-deployment
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
